export const baseItems = [
  "Milk",
  "Eggs",
  "Bread",
  "Butter",
  "Cheese",
  "Yogurt",
  "Chicken",
  "Beef",
  "Pork",
  "Fish",
  "Rice",
  "Pasta",
  "Flour",
  "Sugar",
  "Salt",
  "Pepper",
  "Olive Oil",
  "Vegetable Oil",
  "Vinegar",
  "Soy Sauce",
  "Tomatoes",
  "Onions",
  "Garlic",
  "Potatoes",
  "Carrots",
  "Lettuce",
  "Cucumber",
  "Bell Peppers",
  "Spinach",
  "Broccoli",
  "Apples",
  "Bananas",
  "Oranges",
  "Grapes",
  "Strawberries",
  "Blueberries",
  "Watermelon",
  "Lemons",
  "Limes",
  "Pineapple",
  "Cereal",
  "Oatmeal",
  "Peanut Butter",
  "Jam",
  "Honey",
  "Coffee",
  "Tea",
  "Juice",
  "Soda",
  "Bottled Water",
  "Frozen Vegetables",
  "Frozen Fruit",
  "Ice Cream",
  "Frozen Pizza",
  "Frozen Meals",
  "Canned Beans",
  "Canned Tomatoes",
  "Canned Tuna",
  "Canned Soup",
  "Canned Corn",
  "Bread Crumbs",
  "Baking Powder",
  "Yeast",
  "Chocolate Chips",
  "Cocoa Powder",
  "Chips",
  "Crackers",
  "Popcorn",
  "Nuts",
  "Granola Bars",
  "Toilet Paper",
  "Paper Towels",
  "Tissues",
  "Dish Soap",
  "Laundry Detergent",
  "Fabric Softener",
  "Sponges",
  "Garbage Bags",
  "Aluminum Foil",
  "Plastic Wrap",
  "Shampoo",
  "Conditioner",
  "Body Wash",
  "Soap",
  "Toothpaste",
  "Toothbrushes",
  "Deodorant",
  "Shaving Cream",
  "Razors",
  "Lotion",
  "Dog Food",
  "Cat Food",
  "Baby Formula",
  "Diapers",
  "Baby Wipes",
  "Batteries",
  "Light Bulbs",
  "Matches",
  "First Aid Kit",
  "Hand Sanitizer",
];
